name: Deploy MERN App

on:
  push:
    branches:
      - main

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Code
        uses: actions/checkout@v4

      - name: node setup
        uses: actions/setup-node@v4
        with:
         node-version: 20

      - name: frontend check
        working-directory: ./Frontend 
        run: npm install

      - name: build frontend
        working-directory: ./Frontend
        run: npm run build


      - name: backend check
        working-directory: ./Backend
        run: npm install

  deploy:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd Student-Management
            git pull origin main
            docker compose down
            docker compose up --build -d